# Generated by Django 4.0.6 on 2022-07-12 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(blank=True, help_text='درصد تخفیف', null=True)),
                ('constant', models.PositiveIntegerField(blank=True, help_text='مقدار ثابت تخفیف اگر درصدی نبود', null=True)),
                ('ceil', models.PositiveIntegerField(blank=True, help_text='سقف تخفیف (اگر تخفیف به صورت درصدی است این فیلد را پر کنید)', null=True)),
                ('min_value', models.PositiveIntegerField(blank=True, help_text='حداقل مقدار خرید تا بتواند از کد تخفیف استفاده کند', null=True)),
                ('code', models.CharField(max_length=20, null=True, unique=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('exp_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
        ),
    ]
