# Generated by Django 4.0.6 on 2022-07-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(default='a', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
