# Generated by Django 4.0.6 on 2022-07-14 21:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('discount', '0001_initial'),
        ('shipping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('initial', 'سبد خرید اولیه'), ('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('delivered', 'ارسال شده'), ('canceled', 'کنسل شده')], db_index=True, default='initial', max_length=9, verbose_name='step')),
                ('description', models.TextField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('shipping_price', models.PositiveIntegerField(default=0, help_text='این فیلد به صورت اتوماتیک بعد از نهایی شدن سفارش پر میشود.')),
                ('discount_price', models.PositiveIntegerField(default=0, help_text='این فیلد به صورت اتوماتیک بعد از نهایی شدن سفارش پر میشود.')),
                ('receiver_address', models.TextField(blank=True, null=True)),
                ('delivered_at', models.DateField(blank=True, null=True)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discount.discount')),
                ('shipping', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='shipping.shipping')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField(blank=True, help_text='این فیلد در لحظه ی نهایی شدن سفارش، به صورت اتوماتیک ذخیره میشود', null=True)),
                ('quantity', models.PositiveSmallIntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('created', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='cart.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='product.product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cart.cart',),
            managers=[
                ('order_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
