# Generated by Django 4.0.6 on 2022-07-15 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('-finalized_at',), 'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='created',
            new_name='finalized_at',
        ),
    ]
