# Generated by Django 4.0.6 on 2022-07-14 21:00

from django.db import migrations, models

def create_shipments(apps, schema_editor):
    Shipping = apps.get_model('shipping', 'Shipping')
    Shipping.objects.create(
        type='express',
        price=20000)
    Shipping.objects.create(
        type='regular',
        price=10000)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('regular', 'پست معمولی'), ('express', 'پست پیشتاز')], max_length=12, verbose_name='type')),
                ('price', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Shipping',
                'verbose_name_plural': 'Shipping',
            },
        ),
        # run a python script after migration
        migrations.RunPython(create_shipments, migrations.RunPython.noop)
    ]
